#ifndef _INCLUDE_OKAPI_VERSION_INFORMATION_H_
#define _INCLUDE_OKAPI_VERSION_INFORMATION_H_

/**
 * @file Contains Okapi version information.
 * @brief This file will redirect to an autogenerated version if being compiled via
 * the build scripts.
 */

#if defined OKAPI_GENERATED_BUILD
	#if defined RC_COMPILE
		#undef OKAPI_USE_VERSIONLIB
	#endif
	#if defined OKAPI_USE_VERSIONLIB
		#include <versionlib.h>
	#else 
		#include <okapi_version_auto.h>
	#endif
#else
	#define OKAPI_BUILD_TAG        "manual"
	#define OKAPI_BUILD_LOCAL_REV  "0"
	#define OKAPI_BUILD_CSET       "0"
	#define OKAPI_BUILD_MAJOR      "1"
	#define OKAPI_BUILD_MINOR      "1"
	#define OKAPI_BUILD_RELEASE    "0"

	#define OKAPI_BUILD_UNIQUEID OKAPI_BUILD_LOCAL_REV ":" OKAPI_BUILD_CSET

	#define OKAPI_VERSION_STRING   OKAPI_BUILD_MAJOR "." OKAPI_BUILD_MINOR "." OKAPI_BUILD_RELEASE "-" OKAPI_BUILD_TAG
	#define OKAPI_VERSION_FILE     1,1,0,0
#endif

#define OKAPI_BUILD_TIMESTAMP  __DATE__ " " __TIME__

#if !defined(OKAPI_GENERATED_BUILD) || !defined(OKAPI_USE_VERSIONLIB)
	#define OKAPI_VERSION      OKAPI_VERSION_STRING
	#define OKAPI_BUILD_ID     OKAPI_BUILD_UNIQUEID
	#define OKAPI_BUILD_TIME   OKAPI_BUILD_TIMESTAMP
#endif

#endif /* _INCLUDE_OKAPI_VERSION_INFORMATION_H_ */

